# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import notes_pb2 as notes__pb2


class NoteServiceStub(object):
  """Define All services In Service type


  Implementing Note Service here
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.List = channel.unary_unary(
        '/NoteService/List',
        request_serializer=notes__pb2.Empty.SerializeToString,
        response_deserializer=notes__pb2.NoteList.FromString,
        )
    self.AddNote = channel.unary_unary(
        '/NoteService/AddNote',
        request_serializer=notes__pb2.Note.SerializeToString,
        response_deserializer=notes__pb2.NoteList.FromString,
        )


class NoteServiceServicer(object):
  """Define All services In Service type


  Implementing Note Service here
  """

  def List(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddNote(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NoteServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'List': grpc.unary_unary_rpc_method_handler(
          servicer.List,
          request_deserializer=notes__pb2.Empty.FromString,
          response_serializer=notes__pb2.NoteList.SerializeToString,
      ),
      'AddNote': grpc.unary_unary_rpc_method_handler(
          servicer.AddNote,
          request_deserializer=notes__pb2.Note.FromString,
          response_serializer=notes__pb2.NoteList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'NoteService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
